name: Compile GMpro Deauther Auto-Library

on: [push, workflow_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Arduino CLI
        uses: arduino/setup-arduino-cli@v1

      - name: Install Deauther SDK
        run: |
          arduino-cli core update-index --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json
          arduino-cli core install deauther:esp8266 --additional-urls https://raw.githubusercontent.com/SpacehuhnTech/arduino/main/package_spacehuhn_index.json

      - name: Install All Libraries
        run: |
          # Install semua library lewat CLI agar struktur folder otomatis benar
          arduino-cli lib install "Adafruit GFX Library"
          arduino-cli lib install "Adafruit SSD1306"
          arduino-cli lib install "Adafruit BusIO"
          arduino-cli lib install "SimpleCLI"
          # Versi legacy ArduinoJson untuk Deauther
          arduino-cli lib install "ArduinoJson"@5.13.5

      - name: Compile GMpro Firmware
        run: |
          # Hapus flag --library manual karena CLI sudah tahu folder library-nya
          arduino-cli compile --fqbn deauther:esp8266:d1_mini \
          ./GMpro.ino --output-dir ./build

      - name: Upload Binary
        uses: actions/upload-artifact@v4
        with:
          name: GMpro-Deauther-Binary
          path: ./build/*.bin
